### ISSUE TITLE
Add to home screen banner shows incorrect title

### ISSUE THREAD

**Issue by itaditya** [seanseany/blockchain#1]

**Comment by seanseany** [comment]
Add to home screen banner? Where is that?

**Comment by itaditya** [comment]
On https://blockchaindemo.io

**Comment by seanseany** [comment]
Do you have a screenshot?

**Comment by itaditya** [comment]
![screenshot_2017-11-28-13-46-34-942_com android chrome](https://user-images.githubusercontent.com/15871340/33309005-a9e8bcc4-d442-11e7-854c-dbab9807a48e.png)

**Comment by itaditya** [comment]
You must have added a manifest file, but didn't updated the title

**Comment by seanseany** [comment]
Fixed now! Thanks @itaditya !
