### ISSUE TITLE
Const syntax fails in start in P2p.js

### ISSUE THREAD

**Issue by Skorkmaz88** [seanseany/blockchain#3]
const {
  REQUEST_LATEST_BLOCK,
  RECEIVE_LATEST_BLOCK,
  REQUEST_BLOCKCHAIN,
  RECEIVE_BLOCKCHAIN,
  REQUEST_TRANSACTIONS,
  RECEIVE_TRANSACTIONS
} = messageType;

 This code block causes error with nodejs 6 and 5 on Ubuntu 16.04 system. 

> const {
>       ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:387:25)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/semih/mytone/blockchain/cli.js:2:13)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
> 
> npm ERR! Linux 4.10.0-40-generic
> npm ERR! argv "/home/semih/.nvm/versions/node/v5.12.0/bin/node" "/home/semih/.nvm/versions/node/v5.12.0/bin/npm" "start"
> npm ERR! node v5.12.0
> npm ERR! npm  v3.8.6
> npm ERR! code ELIFECYCLE
> npm ERR! blockchain-cli@2.0.0 start: `node ./index.js`
> npm ERR! Exit status 1
>

**Comment by seanseany** [comment]
Upgrade node

**Comment by Skorkmaz88** [comment]
Of course that is one option :) Would be good to add to docs/ readme.

**Comment by seanseany** [comment]
Would be glad to add it 👍 Anyone know which version of node support this syntax?

**Comment by Skorkmaz88** [comment]
I was able to use it without a problem with node 7. Version 7 and later should be ok I guess

In case one needs to manage versions, here is a great tool: 

https://github.com/creationix/nvm
